/* Auto-generated by tools/sync_symbols.py — do not edit.
 * Source: symbols.toml (Yu-Gi-Oh Forbidden Memories)
 * Progressive symbols: discover → label → manipulate via PSX_FN_*.
 */
#pragma once

/* guessed: SYSTEM.CNF / EXE entry PC (probe seed) */
#define PSX_FN_BootEntry 0x800129D8u
#define func_800129D8 BootEntry  /* alias */
