#!/usr/bin/env python3
"""font_extract.py — bake the game's text font out of a VRAM snapshot.

Yu-Gi-Oh! Forbidden Memories keeps two copies of the same charset in VRAM as
4bpp texture data, both 16 cells per row, 16 texels wide:

    (2560, 0)   8x12 cells    the small font -- the one the duel's card-name
                              bar uses, and the one this bakes
    (2560, 72)  16x16 cells   a larger cut of the same charset

The cell order is ASCII with one seam. Cells 0..57 are ASCII 0x21..0x5A ('!'
through 'Z'), cells 58..63 hold six symbols that are not ASCII at all (a long
arrow and the word END), and cells 64..95 resume at ASCII 0x60. So uppercase
indexes as `ascii - 0x21` and lowercase as `ascii - 0x20`, which is what
PSX_FUSION_FONT_CELL in the header encodes. Verified by decoding the cell the
map sends 'A' to and reading the bitmap: a triangle with a crossbar.

The 4-bit value is a brightness ramp, not an arbitrary palette index: 0 is
transparent, 1 is the dark outline the game draws around every glyph, and the
high values are the white core. Checked by decoding 'F' and laying it beside
the same letter as it appears in the duel's card-name bar in the framebuffer --
nine rows of ink on an eight-pixel advance, identical shape. So baking the raw
value and ramping it to grey at draw time reproduces the game's own anti-
aliased white text without tracking a CLUT. One byte per pixel: bigger than
packed nibbles, and it keeps the generated table readable.

    font_extract.py emit <snap> <out.c>
"""

import os
import sys

VRAM_W = 1024                       # 16-bit words per VRAM row
SNAPDIR = os.environ.get(
    "PSX_VRAMDIR",
    os.path.join(os.environ.get("TEMP", "."), "claude", "ygofm-vram"))

CELLS = 96
COLS = 16
FONTS = [("small", 2560, 0, 8, 12)]

# The two stat icons the game prints beside a card's attack and defence, from
# the same 8bpp card-stat sheet the digits come from. Emitted as ARGB through
# that sheet's CLUT rather than as coverage: unlike the font these are real
# two-tone art, not a brightness ramp.
ICONS = [("atk", 1912, 368, 8, 8), ("def", 1912, 376, 8, 8)]
ICON_CLUT = (256, 241)


def load(name):
    with open(os.path.join(SNAPDIR, name + ".bin"), "rb") as f:
        return f.read()


def px16(v):
    r = (v & 0x1F) << 3
    g = ((v >> 5) & 0x1F) << 3
    b = ((v >> 10) & 0x1F) << 3
    return r | (r >> 5), g | (g >> 5), b | (b >> 5)


def idx8(vram, x, y):
    return vram[y * VRAM_W * 2 + x]


def clut(vram, cx, cy, n=256):
    out = []
    for i in range(n):
        v = int.from_bytes(vram[(cy * VRAM_W + cx + i) * 2:][:2], "little")
        out.append(None if v == 0 else px16(v))
    return out


def icon_argb(vram, ox, oy, w, h, pal):
    px = []
    for y in range(h):
        for x in range(w):
            c = pal[idx8(vram, ox + x, oy + y)]
            px.append(0 if c is None else (0xFF000000 | (c[0] << 16) |
                                           (c[1] << 8) | c[2]))
    return px


def idx4(vram, x, y):
    b = vram[y * VRAM_W * 2 + (x >> 1)]
    return (b & 0xF) if (x & 1) == 0 else (b >> 4)


def cells(vram, ox, oy, cw, ch):
    out = []
    for c in range(CELLS):
        cx = ox + (c % COLS) * cw
        cy = oy + (c // COLS) * ch
        out.append([idx4(vram, cx + x, cy + y)
                    for y in range(ch) for x in range(cw)])
    return out


def emit(snap, path):
    vram = load(snap)
    with open(path, "w", newline="\n") as f:
        f.write("/* Generated by tools/font_extract.py - DO NOT EDIT BY HAND.\n"
                " *\n"
                " * The game's own text font, lifted from VRAM as 4-bit\n"
                " * coverage. See psx_fusion_font.h for the cell mapping.\n"
                " */\n\n#include \"psx_fusion_font.h\"\n\n")
        for name, ox, oy, cw, ch in FONTS:
            data = cells(vram, ox, oy, cw, ch)
            ink = sum(1 for g in data for v in g if v)
            f.write("/* %s: VRAM 4bpp (%d,%d), %d cells of %dx%d, %d inked "
                    "texels */\n" % (name, ox, oy, CELLS, cw, ch, ink))
            f.write("static const uint8_t k_%s[%d * %d * %d] = {\n"
                    % (name, CELLS, cw, ch))
            for c, g in enumerate(data):
                f.write("    /* cell %2d */ " % c)
                f.write(",".join(str(v) for v in g))
                f.write(",\n")
            f.write("};\n\n")
        f.write("const PsxFusionFont psx_fusion_font = { k_small, 8, 12 };\n\n")
        pal = clut(vram, *ICON_CLUT)
        for name, ox, oy, w, h in ICONS:
            px = icon_argb(vram, ox, oy, w, h, pal)
            f.write("/* %s icon: VRAM 8bpp (%d,%d) %dx%d through CLUT (%d,%d) */\n"
                    % (name, ox, oy, w, h, ICON_CLUT[0], ICON_CLUT[1]))
            f.write("static const uint32_t k_icon_%s[%d] = {\n    " % (name, w * h))
            f.write(",".join("0x%08Xu" % v for v in px))
            f.write(",\n};\n")
            f.write("const PsxSprite psx_fusion_icon_%s = { k_icon_%s, %d, %d };\n\n"
                    % (name, name, w, h))
    print("wrote", path)


if __name__ == "__main__":
    if len(sys.argv) != 4 or sys.argv[1] != "emit":
        sys.exit(__doc__)
    emit(sys.argv[2], sys.argv[3])
