#!/usr/bin/env python3
"""gen_duelist_icons.py — bake the FREE DUEL portraits into C.

    gen_duelist_icons.py <png_dir> <out_dir>

Input is a directory of `duelist_NN.png`, NN being the duelist index the drop
tables use. Output is `psx_duelist_icons.c` in the build directory: Konami art,
so build output and not source, exactly like the sprites and font.

CAPTURING THE PNGs
------------------
They are not derived from the disc — the portrait atlas is compressed there and
was not found by searching for its VRAM bytes. They come off a running game
instead, which is what `tools/duelist_icons.py` (single VRAM snapshot) and the
session's collector do. What made the capture reliable was not the art but two
observations about the FREE DUEL screen:

  * `0x8009B32E` holds the highlighted duelist's index + 41, so the identity of
    what is on screen is READ rather than counted. Byte 40 is the Build Deck
    button, which occupies the grid's first cell and is not a duelist.
  * the cursor's border animates, so two screenshots taken at rest differ in
    exactly one place — the highlighted cell.

Together those turn "walk the grid and hope the presses land" into something
self-verifying, which matters because presses on that screen are unreliable: a
short hold does nothing at all and reads exactly like a soft-lock.

A missing index is normal and is emitted as NULL. The free-duel list does not
carry the story-only opponents, and it does not carry anyone still unbeaten.
"""

import os
import re
import sys

N = 39
W = H = 38


def load_png(path):
    """RGBA rows via PIL if present, else a minimal inflate of the IDAT."""
    try:
        from PIL import Image
        im = Image.open(path).convert('RGBA').resize((W, H))
        return list(im.getdata())
    except ImportError:
        raise SystemExit('gen_duelist_icons.py needs PIL to read the PNGs')


def main():
    if len(sys.argv) < 3:
        raise SystemExit('usage: gen_duelist_icons.py <png_dir> <out_dir>')
    src, out_dir = sys.argv[1], sys.argv[2]
    os.makedirs(out_dir, exist_ok=True)

    icons = {}
    if os.path.isdir(src):
        for name in os.listdir(src):
            m = re.fullmatch(r'duelist_(\d{2})\.png', name)
            if not m:
                continue
            i = int(m.group(1))
            if 0 <= i < N:
                icons[i] = load_png(os.path.join(src, name))

    L = []
    L.append('/* psx_duelist_icons.c — GENERATED by tools/gen_duelist_icons.py.')
    L.append(' * Build output, not source: do not commit. See the header. */')
    L.append('#include "psx_duelist_icons.h"')
    L.append('')
    for i in sorted(icons):
        L.append('static const uint32_t ICON_%02d[%d] = {' % (i, W * H))
        px = icons[i]
        line = '   '
        for (r, g, b, a) in px:
            item = ' 0x%02X%02X%02X%02Xu,' % (a, r, g, b)
            if len(line) + len(item) > 78:
                L.append(line)
                line = '   '
            line += item
        if line.strip():
            L.append(line)
        L.append('};')
    L.append('')
    L.append('const uint32_t *const PSX_DUELIST_ICONS[PSX_DUELIST_ICON_N] = {')
    for i in range(N):
        L.append('    %s,' % (('ICON_%02d' % i) if i in icons else '0'))
    L.append('};')
    L.append('')
    path = os.path.join(out_dir, 'psx_duelist_icons.c')
    with open(path, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(L) + '\n')
    print('gen_duelist_icons: wrote %s (%d of %d duelists)'
          % (path, len(icons), N))


if __name__ == '__main__':
    main()
